name: CI/CD Docker Enterprise Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - folder: config-server
            tag: config-server

          - folder: discovery-server
            tag: discovery-server

          - folder: auth-service
            tag: auth-service

          - folder: incident-service
            tag: incident-service

          - folder: moderation-service
            tag: moderation-service

          - folder: gateway-service
            tag: gateway-service

          - folder: IncidentManagementSystem-front
            tag: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Login (mandatory before push)
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Setup buildx (for cache + performance)
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build + Push
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.folder }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.tag }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.tag }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max